/**
 * Krea model catalog — API path segments from https://docs.krea.ai (Model APIs).
 * Add new models here; do not hardcode model lists in UI components.
 */

import type { KreaModelConfig } from "./krea-model-registry";
import { KREA_MODEL_REGISTRY_EXT } from "./krea-model-registry-ext";

type RegistryEntryInput = Omit<
  KreaModelConfig,
  "internalModel" | "descriptionEn" | "descriptionDe"
> & {
  internalModel?: string;
  /** @deprecated Use internalModel */
  model?: string;
  descriptionEn?: string;
  descriptionDe?: string;
  /** @deprecated Use descriptionEn */
  description?: string;
};

/** Factory keeps entries consistent; internalModel = Krea API path after /generate/{kind}/ */
function m(entry: RegistryEntryInput): KreaModelConfig {
  const internalModel = (entry.internalModel ?? entry.model ?? "").replace(
    /^\/+/,
    ""
  );
  const descriptionEn =
    entry.descriptionEn ?? entry.description ?? entry.label;
  const descriptionDe = entry.descriptionDe ?? descriptionEn;
  const endpointKind =
    entry.endpointKind ??
    (entry.category === "video"
      ? "video"
      : entry.category === "enhancer"
        ? "enhance"
        : entry.category === "training" || entry.category === "style_training"
          ? "training"
          : "image");

  return {
    ...entry,
    internalModel,
    model: internalModel,
    descriptionEn,
    descriptionDe,
    endpointKind,
  };
}

export const KREA_MODEL_REGISTRY_ENTRIES: readonly KreaModelConfig[] = [
  // —— Krea proprietary ——
  m({
    id: "krea-2-large",
    label: "Krea 2 Large",
    provider: "krea",
    model: "krea/krea-2/large",
    category: "image",
    tools: ["image", "brand_assets", "product_photography", "campaign_builder"],
    capabilities: ["text_to_image", "image_to_image"],
    description: "Expressive photorealism; moodboards and style references.",
    credits: 3,
    availability: "active",
    outputType: "image",
    isRecommended: true,
    workflowKeys: ["premium_image", "standard"],
  }),
  m({
    id: "krea-2-medium",
    label: "Krea 2 Medium",
    provider: "krea",
    model: "krea/krea-2/medium",
    category: "image",
    tools: ["image", "realtime", "batch_generator"],
    capabilities: ["text_to_image"],
    description: "Expressive illustrations and fast creative drafts.",
    credits: 2,
    availability: "active",
    outputType: "image",
    workflowKeys: ["fast_draft"],
  }),

  // —— Flux / BFL ——
  m({
    id: "flux-1-dev",
    label: "Flux 1 Dev",
    provider: "krea",
    model: "bfl/flux-1-dev",
    category: "image",
    tools: ["image", "realtime", "batch_generator"],
    capabilities: ["text_to_image", "image_to_image"],
    description: "Fast baseline; LoRA-friendly.",
    credits: 1,
    availability: "experimental",
    outputType: "image",
    workflowKeys: ["standard", "fast_draft", "ugc_look"],
    envOverride: "KREA_MODEL_STANDARD",
  }),
  m({
    id: "flux-11-pro",
    label: "Flux 1.1 Pro",
    provider: "krea",
    model: "bfl/flux-1.1-pro",
    category: "image",
    tools: ["image", "brand_assets", "product_photography"],
    capabilities: ["text_to_image"],
    description: "Higher quality Flux generation.",
    credits: 3,
    availability: "experimental",
    outputType: "image",
    isPremium: true,
    workflowKeys: ["premium_image", "brand_assets"],
    envOverride: "KREA_MODEL_PREMIUM",
  }),
  m({
    id: "flux-11-pro-ultra",
    label: "Flux 1.1 Pro Ultra",
    provider: "krea",
    model: "bfl/flux-1.1-pro-ultra",
    category: "image",
    tools: ["image", "brand_assets"],
    capabilities: ["text_to_image"],
    description: "BFL highest-quality text-to-image.",
    credits: 4,
    availability: "experimental",
    outputType: "image",
    isPremium: true,
  }),
  m({
    id: "flux-kontext",
    label: "Flux Kontext",
    provider: "krea",
    model: "bfl/flux-1-kontext-dev",
    category: "edit",
    tools: ["edit", "video_restyle"],
    capabilities: ["edit", "image_to_image"],
    description: "Image editing and kontext transforms.",
    credits: 5,
    availability: "experimental",
    outputType: "image",
    requires: ["source_image_url"],
    workflowKeys: ["reference_edit"],
  }),

  // —— Google ——
  m({
    id: "nano-banana-pro",
    label: "Nano Banana Pro",
    provider: "krea",
    model: "google/nano-banana-pro",
    category: "edit",
    tools: ["edit", "video_restyle", "image"],
    capabilities: ["edit", "image_to_image", "text_to_image"],
    description: "Reference edit and semantic image changes.",
    credits: 5,
    availability: "experimental",
    outputType: "image",
    requires: ["source_image_url"],
    workflowKeys: ["reference_edit"],
    envOverride: "KREA_MODEL_REFERENCE_EDIT",
  }),
  m({
    id: "nano-banana",
    label: "Nano Banana",
    provider: "krea",
    model: "google/nano-banana",
    category: "image",
    tools: ["image", "realtime"],
    capabilities: ["text_to_image", "image_to_image"],
    credits: 2,
    availability: "active",
    outputType: "image",
  }),
  m({
    id: "nano-banana-2",
    label: "Nano Banana 2",
    provider: "krea",
    model: "google/nano-banana-2",
    category: "image",
    tools: ["image", "realtime"],
    capabilities: ["text_to_image"],
    credits: 2,
    availability: "experimental",
    outputType: "image",
  }),
  m({
    id: "imagen-4",
    label: "Imagen 4",
    provider: "krea",
    model: "google/imagen-4",
    category: "image",
    tools: ["image", "product_photography", "brand_assets"],
    capabilities: ["text_to_image"],
    description: "Google photorealism and prompt adherence.",
    credits: 3,
    availability: "experimental",
    outputType: "image",
    isPremium: true,
  }),
  m({
    id: "imagen-4-fast",
    label: "Imagen 4 Fast",
    provider: "krea",
    model: "google/imagen-4-fast",
    category: "image",
    tools: ["image", "realtime"],
    capabilities: ["text_to_image"],
    credits: 2,
    availability: "experimental",
    outputType: "image",
  }),
  m({
    id: "imagen-4-ultra",
    label: "Imagen 4 Ultra",
    provider: "krea",
    model: "google/imagen-4-ultra",
    category: "image",
    tools: ["image", "brand_assets"],
    capabilities: ["text_to_image"],
    credits: 4,
    availability: "experimental",
    outputType: "image",
    isPremium: true,
  }),
  m({
    id: "imagen-3",
    label: "Imagen 3",
    provider: "krea",
    model: "google/imagen-3",
    category: "image",
    tools: ["image"],
    capabilities: ["text_to_image"],
    credits: 2,
    availability: "experimental",
    outputType: "image",
  }),

  // —— OpenAI (GPT-IMG) ——
  m({
    id: "gpt-image",
    label: "GPT Image",
    provider: "krea",
    model: "openai/gpt-image",
    category: "image",
    tools: ["image", "edit", "campaign_builder"],
    capabilities: ["text_to_image", "edit", "image_to_image"],
    description: "ChatGPT image (GPT-IMG) with multi-reference support.",
    credits: 4,
    availability: "not_configured",
    outputType: "image",
    isPremium: true,
  }),
  m({
    id: "gpt-image-2",
    label: "GPT Image 2",
    provider: "krea",
    model: "openai/gpt-image-2",
    category: "edit",
    tools: ["edit", "image"],
    capabilities: ["edit", "image_to_image", "text_to_image"],
    description: "Smart editing with up to 4K output.",
    credits: 5,
    availability: "not_configured",
    outputType: "image",
    isPremium: true,
  }),

  // —— ByteDance ——
  m({
    id: "seedream-4",
    label: "Seedream 4",
    provider: "krea",
    model: "bytedance/seedream-4",
    category: "image",
    tools: ["image", "product_photography"],
    capabilities: ["text_to_image"],
    credits: 2,
    availability: "experimental",
    outputType: "image",
  }),
  m({
    id: "seedream-5-lite",
    label: "Seedream 5 Lite",
    provider: "krea",
    model: "bytedance/seedream-5-lite",
    category: "image",
    tools: ["image", "realtime"],
    capabilities: ["text_to_image"],
    credits: 1,
    availability: "experimental",
    outputType: "image",
  }),
  m({
    id: "seededit",
    label: "SeedEdit",
    provider: "krea",
    model: "bytedance/seededit",
    category: "edit",
    tools: ["edit"],
    capabilities: ["edit", "image_to_image"],
    credits: 5,
    availability: "experimental",
    outputType: "image",
    requires: ["source_image_url"],
  }),

  // —— Runway (image) ——
  m({
    id: "runway-gen-4-image",
    label: "Runway Gen-4",
    provider: "krea",
    model: "runway/gen-4",
    category: "image",
    tools: ["image", "brand_assets", "video_restyle"],
    capabilities: ["text_to_image", "image_to_image"],
    credits: 3,
    availability: "experimental",
    outputType: "image",
  }),

  // —— Ideogram / Qwen / Luma / Z ——
  m({
    id: "ideogram-30",
    label: "Ideogram 3.0",
    provider: "krea",
    model: "ideogram/ideogram-3.0",
    category: "image",
    tools: ["image", "brand_assets"],
    capabilities: ["text_to_image"],
    credits: 2,
    availability: "experimental",
    outputType: "image",
  }),
  m({
    id: "qwen-2512",
    label: "Qwen 2512",
    provider: "krea",
    model: "qwen/qwen-2512",
    category: "image",
    tools: ["image", "product_photography"],
    capabilities: ["text_to_image"],
    credits: 1,
    availability: "experimental",
    outputType: "image",
  }),
  m({
    id: "luma-uni-1",
    label: "Luma UNI-1",
    provider: "krea",
    model: "luma/uni-1",
    category: "image",
    tools: ["image"],
    capabilities: ["text_to_image"],
    credits: 2,
    availability: "experimental",
    outputType: "image",
  }),
  m({
    id: "z-image",
    label: "Z Image",
    provider: "krea",
    model: "krea/z-image",
    category: "realtime",
    tools: ["realtime", "image"],
    capabilities: ["text_to_image"],
    description: "Fast photorealistic drafts.",
    credits: 1,
    availability: "experimental",
    outputType: "image",
  }),

  // —— Video: Kling ——
  m({
    id: "kling-3",
    label: "Kling 3.0",
    provider: "krea",
    model: "kling/kling-3.0",
    category: "video",
    tools: ["video"],
    capabilities: ["text_to_video", "image_to_video"],
    description: "Frontier motion with optional native audio.",
    credits: 25,
    availability: "experimental",
    outputType: "video",
    isRecommended: true,
    workflowKeys: ["video_image_to_video"],
  }),
  m({
    id: "kling-26",
    label: "Kling 2.6",
    provider: "krea",
    model: "kling/kling-2.6",
    category: "video",
    tools: ["video"],
    capabilities: ["text_to_video", "image_to_video"],
    credits: 22,
    availability: "experimental",
    outputType: "video",
  }),
  m({
    id: "kling-25",
    label: "Kling 2.5",
    provider: "krea",
    model: "kling/kling-2.5",
    category: "video",
    tools: ["video"],
    capabilities: ["image_to_video"],
    credits: 25,
    availability: "experimental",
    outputType: "video",
    workflowKeys: ["video_image_to_video"],
    envOverride: "KREA_MODEL_VIDEO",
  }),
  m({
    id: "kling-o1",
    label: "Kling o1",
    provider: "krea",
    model: "kling/kling-o1",
    category: "video",
    tools: ["video"],
    capabilities: ["text_to_video", "image_to_video"],
    credits: 28,
    availability: "experimental",
    outputType: "video",
  }),

  // —— Video: Google Veo ——
  m({
    id: "veo-31",
    label: "Veo 3.1",
    provider: "krea",
    model: "google/veo-3.1",
    category: "video",
    tools: ["video", "campaign_builder"],
    capabilities: ["text_to_video", "image_to_video"],
    description: "Highest-quality Veo with audio.",
    credits: 30,
    availability: "experimental",
    outputType: "video",
    isPremium: true,
  }),
  m({
    id: "veo-31-fast",
    label: "Veo 3.1 Fast",
    provider: "krea",
    model: "google/veo-3.1-fast",
    category: "video",
    tools: ["video"],
    capabilities: ["text_to_video", "image_to_video"],
    credits: 22,
    availability: "experimental",
    outputType: "video",
  }),
  m({
    id: "veo-3",
    label: "Veo 3",
    provider: "krea",
    model: "google/veo-3",
    category: "video",
    tools: ["video"],
    capabilities: ["text_to_video", "image_to_video"],
    credits: 28,
    availability: "experimental",
    outputType: "video",
  }),
  m({
    id: "veo-3-fast",
    label: "Veo 3 Fast",
    provider: "krea",
    model: "google/veo-3-fast",
    category: "video",
    tools: ["video"],
    capabilities: ["text_to_video", "image_to_video"],
    credits: 20,
    availability: "experimental",
    outputType: "video",
  }),

  // —— Video: Runway / Seedance / others ——
  m({
    id: "runway-gen-45",
    label: "Runway Gen-4.5",
    provider: "krea",
    model: "runway/gen-4.5",
    category: "video",
    tools: ["video", "video_restyle"],
    capabilities: ["text_to_video", "image_to_video", "video_to_video"],
    credits: 28,
    availability: "experimental",
    outputType: "video",
    isPremium: true,
  }),
  m({
    id: "seedance-pro",
    label: "Seedance Pro",
    provider: "krea",
    model: "bytedance/seedance-1.0-pro",
    category: "video",
    tools: ["video"],
    capabilities: ["text_to_video", "image_to_video"],
    credits: 22,
    availability: "experimental",
    outputType: "video",
  }),
  m({
    id: "seedance-pro-fast",
    label: "Seedance Pro Fast",
    provider: "krea",
    model: "bytedance/seedance-1.0-pro-fast",
    category: "video",
    tools: ["video"],
    capabilities: ["text_to_video", "image_to_video"],
    credits: 18,
    availability: "experimental",
    outputType: "video",
  }),
  m({
    id: "hailuo-23",
    label: "Hailuo 2.3",
    provider: "krea",
    model: "minimax/hailuo-2.3",
    category: "video",
    tools: ["video"],
    capabilities: ["text_to_video", "image_to_video"],
    credits: 20,
    availability: "experimental",
    outputType: "video",
  }),
  m({
    id: "wan-25",
    label: "Wan 2.5",
    provider: "krea",
    model: "alibaba/wan-2.5",
    category: "video",
    tools: ["video"],
    capabilities: ["text_to_video", "image_to_video"],
    credits: 15,
    availability: "experimental",
    outputType: "video",
  }),
  m({
    id: "grok-imagine-video",
    label: "Grok Imagine",
    provider: "krea",
    model: "xai/grok-imagine",
    category: "video",
    tools: ["video"],
    capabilities: ["text_to_video"],
    credits: 18,
    availability: "experimental",
    outputType: "video",
  }),
  m({
    id: "sora-2",
    label: "Sora 2",
    provider: "krea",
    model: "openai/sora-2",
    category: "video",
    tools: ["video", "campaign_builder"],
    capabilities: ["text_to_video"],
    description: "OpenAI Sora via Krea API when enabled on your Krea account.",
    credits: 35,
    availability: "experimental",
    outputType: "video",
    isPremium: true,
  }),

  // —— Enhancer ——
  m({
    id: "topaz-standard",
    label: "Topaz Standard",
    provider: "krea",
    model: "topaz/standard-enhance",
    category: "enhancer",
    endpointKind: "enhance",
    tools: ["enhancer"],
    capabilities: ["enhance", "upscale"],
    credits: 4,
    availability: "experimental",
    outputType: "image",
    isRecommended: true,
    requires: ["source_image_url"],
    workflowKeys: ["enhance_asset"],
    envOverride: "KREA_MODEL_ENHANCE",
  }),
  m({
    id: "topaz-bloom",
    label: "Topaz Bloom",
    provider: "krea",
    model: "topaz/bloom",
    category: "enhancer",
    endpointKind: "enhance",
    tools: ["enhancer"],
    capabilities: ["enhance", "upscale"],
    credits: 5,
    availability: "experimental",
    outputType: "image",
    requires: ["source_image_url"],
  }),
  m({
    id: "topaz-generative",
    label: "Topaz Generative",
    provider: "krea",
    model: "topaz/generative",
    category: "enhancer",
    endpointKind: "enhance",
    tools: ["enhancer"],
    capabilities: ["enhance", "upscale"],
    credits: 6,
    availability: "experimental",
    outputType: "image",
    isPremium: true,
    requires: ["source_image_url"],
  }),

  // —— 3D (image-render proxy until dedicated mesh endpoint is wired) ——
  m({
    id: "krea-3d-render",
    label: "3D Product Render",
    provider: "krea",
    model: "krea/krea-2/large",
    category: "3d",
    tools: ["3d_objects", "product_photography"],
    capabilities: ["3d_object", "text_to_image"],
    descriptionEn: "Photoreal 3D-style renders (dedicated mesh API planned).",
    descriptionDe: "Fotorealistische 3D-Renderings (dedizierte Mesh-API geplant).",
    credits: 3,
    availability: "experimental",
    outputType: "image",
  }),

  // —— Extended catalog (not_configured until wired) ——
  ...KREA_MODEL_REGISTRY_EXT,

  // —— Legacy placeholders ——
  m({
    id: "lipsync-pending",
    label: "Lip Sync Studio",
    provider: "krea",
    internalModel: "pending/lipsync",
    category: "lipsync",
    tools: ["lipsync"],
    capabilities: ["lipsync", "audio_to_video"],
    descriptionEn: "Talking-head lip sync — Krea endpoint not wired yet.",
    descriptionDe: "Talking-Head Lip-Sync — Krea-Endpunkt noch nicht angebunden.",
    credits: 30,
    availability: "not_configured",
    outputType: "video",
    requires: ["source_video_url", "audio_url"],
  }),
  m({
    id: "motion-transfer-pending",
    label: "Motion Transfer",
    provider: "krea",
    internalModel: "pending/motion-transfer",
    category: "motion_transfer",
    tools: ["motion_transfer"],
    capabilities: ["motion_transfer", "image_to_video"],
    descriptionEn: "Portrait motion transfer — Krea endpoint not wired yet.",
    descriptionDe: "Portrait-Motion-Transfer — Krea-Endpunkt noch nicht angebunden.",
    credits: 25,
    availability: "not_configured",
    outputType: "video",
    requires: ["source_image_url", "driving_video_url"],
  }),
  m({
    id: "audio-pending",
    label: "Voice & Audio",
    provider: "krea",
    internalModel: "pending/audio",
    category: "audio",
    tools: ["audio"],
    capabilities: ["text_to_audio"],
    descriptionEn: "Text-to-speech and voiceover — Krea endpoint not wired yet.",
    descriptionDe: "Text-zu-Sprache und Voiceover — Krea-Endpunkt noch nicht angebunden.",
    credits: 5,
    availability: "not_configured",
    outputType: "audio",
  }),
  m({
    id: "apps-workflow-pending",
    label: "Creative Apps",
    provider: "krea",
    internalModel: "pending/apps",
    category: "workflow",
    tools: ["apps"],
    capabilities: ["workflow", "planning"],
    descriptionEn: "Multi-step creative apps — orchestration not wired yet.",
    descriptionDe: "Multi-Step Creative Apps — Orchestrierung noch nicht angebunden.",
    credits: 0,
    availability: "not_configured",
    outputType: "text",
  }),
  m({
    id: "style-profiles-pending",
    label: "Style Profiles",
    provider: "krea",
    internalModel: "pending/style-profiles",
    category: "workflow",
    tools: ["style_profiles"],
    capabilities: ["workflow", "image_to_image"],
    descriptionEn: "Character and style profile training — not wired yet.",
    descriptionDe: "Charakter- und Style-Profile — noch nicht angebunden.",
    credits: 0,
    availability: "not_configured",
    outputType: "text",
  }),

  // —— LoRA / Style Training (Krea styles/train — not image generate) ——
  m({
    id: "style_lora_training",
    label: "Style LoRA Training",
    provider: "krea",
    internalModel: "styles/train",
    category: "training",
    tools: ["train_lora", "style_profiles", "style_training"],
    capabilities: ["train_lora", "train_style", "custom_style"],
    descriptionEn:
      "Train a reusable visual style from reference images and apply it to future campaign assets.",
    descriptionDe:
      "Trainiere einen wiederverwendbaren visuellen Stil aus Referenzbildern und nutze ihn für zukünftige Kampagnenassets.",
    credits: 100,
    outputType: "style",
    availability: "experimental",
    isRecommended: true,
    requires: ["reference_images"],
    workflowKeys: ["train_style"],
  }),
  m({
    id: "character_lora_training",
    label: "Character LoRA Training",
    provider: "krea",
    internalModel: "styles/train",
    category: "training",
    tools: ["train_lora", "style_profiles", "style_training"],
    capabilities: ["train_lora", "train_character", "custom_style"],
    descriptionEn:
      "Train a consistent creator or character identity from a curated image set.",
    descriptionDe:
      "Trainiere eine konsistente Creator- oder Character-Identität aus einem kuratierten Bildset.",
    credits: 150,
    outputType: "style",
    availability: "experimental",
    requires: ["reference_images"],
    workflowKeys: ["train_character"],
  }),
  m({
    id: "object_product_lora_training",
    label: "Product / Object LoRA Training",
    provider: "krea",
    internalModel: "styles/train",
    category: "training",
    tools: ["train_lora", "product_photography", "brand_assets", "style_training"],
    capabilities: ["train_lora", "train_object", "train_product", "custom_style"],
    descriptionEn:
      "Train a product or object style for repeatable product visuals and brand assets.",
    descriptionDe:
      "Trainiere einen Produkt- oder Objektstil für wiederholbare Produktvisuals und Brand Assets.",
    credits: 150,
    outputType: "style",
    availability: "experimental",
    requires: ["reference_images"],
    workflowKeys: ["train_product"],
  }),
  m({
    id: "brand_style_training",
    label: "Brand Style Training",
    provider: "krea",
    internalModel: "styles/train",
    category: "training",
    tools: ["train_lora", "brand_assets", "style_profiles", "style_training"],
    capabilities: ["train_lora", "train_style", "custom_style"],
    descriptionEn:
      "Create a reusable brand style system for consistent campaigns across formats.",
    descriptionDe:
      "Erstelle ein wiederverwendbares Markenstil-System für konsistente Kampagnen über mehrere Formate hinweg.",
    credits: 200,
    outputType: "style",
    availability: "experimental",
    isPremium: true,
    requires: ["reference_images"],
    workflowKeys: ["train_brand"],
  }),

] as const;
