/**
 * Extended Krea catalog entries — API paths unconfirmed entries use not_configured.
 * @see https://docs.krea.ai
 */

import type { KreaModelConfig } from "./krea-model-registry";

type RegistryEntryInput = Omit<
  KreaModelConfig,
  "internalModel" | "descriptionEn" | "descriptionDe"
> & {
  internalModel?: string;
  model?: string;
  descriptionEn?: string;
  descriptionDe?: string;
  description?: string;
};

function m(entry: RegistryEntryInput): KreaModelConfig {
  const internalModel = (entry.internalModel ?? entry.model ?? "").replace(
    /^\/+/,
    ""
  );
  const descriptionEn =
    entry.descriptionEn ?? entry.description ?? entry.label;
  const descriptionDe = entry.descriptionDe ?? descriptionEn;
  const endpointKind =
    entry.endpointKind ??
    (entry.category === "video"
      ? "video"
      : entry.category === "enhancer"
        ? "enhance"
        : "image");

  return {
    ...entry,
    internalModel,
    model: internalModel,
    descriptionEn,
    descriptionDe,
    endpointKind,
  };
}

/** Additional registry rows — import into krea-model-registry-data.ts */
export const KREA_MODEL_REGISTRY_EXT: readonly KreaModelConfig[] = [
  // —— Image (extended) ——
  m({
    id: "flux-2-pro",
    label: "Flux 2 Pro",
    provider: "krea",
    internalModel: "pending/flux-2-pro",
    category: "image",
    tools: ["image", "brand_assets"],
    capabilities: ["text_to_image"],
    descriptionEn: "Next-gen Flux Pro — API path pending confirmation.",
    descriptionDe: "Flux Pro der nächsten Generation — API-Pfad noch nicht bestätigt.",
    credits: 4,
    availability: "not_configured",
    outputType: "image",
    isPremium: true,
  }),
  m({
    id: "flux-2-dev",
    label: "Flux 2 Dev",
    provider: "krea",
    internalModel: "pending/flux-2-dev",
    category: "image",
    tools: ["image", "realtime", "batch_generator"],
    capabilities: ["text_to_image"],
    descriptionEn: "Fast Flux 2 dev tier — API path pending confirmation.",
    descriptionDe: "Schnelle Flux-2-Dev-Stufe — API-Pfad noch nicht bestätigt.",
    credits: 2,
    availability: "not_configured",
    outputType: "image",
  }),
  m({
    id: "recraft-v41",
    label: "Recraft V4.1",
    provider: "krea",
    internalModel: "pending/recraft-v4.1",
    category: "image",
    tools: ["image", "brand_assets"],
    capabilities: ["text_to_image"],
    credits: 3,
    availability: "not_configured",
    outputType: "image",
  }),
  m({
    id: "krea-1",
    label: "Creator Photo Engine",
    provider: "krea",
    internalModel: "pending/krea-1",
    category: "image",
    tools: ["image", "product_photography"],
    capabilities: ["text_to_image", "image_to_image"],
    descriptionEn: "Creator-focused photo engine (Krea 1 lineage).",
    descriptionDe: "Creator-fokussierte Foto-Engine (Krea-1-Linie).",
    credits: 2,
    availability: "not_configured",
    outputType: "image",
  }),
  m({
    id: "smart-auto-pilot",
    label: "Smart Auto-Pilot",
    provider: "krea",
    internalModel: "resolver/smart-auto-pilot",
    category: "workflow",
    tools: ["image"],
    capabilities: ["text_to_image", "workflow"],
    descriptionEn: "Routes to a verified default image engine.",
    descriptionDe: "Nutzt automatisch eine verifizierte Standard-Bild-Engine.",
    credits: 1,
    availability: "active",
    outputType: "image",
  }),

  // —— Video (extended) ——
  m({
    id: "kling-o3",
    label: "Kling O3",
    provider: "krea",
    internalModel: "pending/kling-o3",
    category: "video",
    tools: ["video"],
    capabilities: ["text_to_video", "image_to_video"],
    credits: 30,
    availability: "not_configured",
    outputType: "video",
    isPremium: true,
  }),
  m({
    id: "runway-motion-pro",
    label: "Runway Motion Pro",
    provider: "krea",
    internalModel: "pending/runway-motion-pro",
    category: "video",
    tools: ["video", "motion_transfer"],
    capabilities: ["image_to_video", "motion_transfer"],
    credits: 28,
    availability: "not_configured",
    outputType: "video",
  }),
  m({
    id: "hailuo-fast",
    label: "Hailuo Fast Engine",
    provider: "krea",
    internalModel: "pending/hailuo-fast",
    category: "video",
    tools: ["video"],
    capabilities: ["text_to_video", "image_to_video"],
    credits: 18,
    availability: "not_configured",
    outputType: "video",
  }),
  m({
    id: "seedance-character-retain",
    label: "Seedance Character Retain",
    provider: "krea",
    internalModel: "pending/seedance-character-retain",
    category: "video",
    tools: ["video"],
    capabilities: ["image_to_video"],
    credits: 22,
    availability: "not_configured",
    outputType: "video",
  }),
  m({
    id: "wan-27",
    label: "Wan 2.7",
    provider: "krea",
    internalModel: "pending/wan-2.7",
    category: "video",
    tools: ["video"],
    capabilities: ["text_to_video", "image_to_video"],
    credits: 18,
    availability: "not_configured",
    outputType: "video",
  }),
  m({
    id: "pixverse-v6",
    label: "PixVerse V6",
    provider: "krea",
    internalModel: "pending/pixverse-v6",
    category: "video",
    tools: ["video"],
    capabilities: ["text_to_video", "image_to_video"],
    credits: 20,
    availability: "not_configured",
    outputType: "video",
  }),
  m({
    id: "ltx-2-fast",
    label: "LTX-2 Fast",
    provider: "krea",
    internalModel: "pending/ltx-2-fast",
    category: "video",
    tools: ["video"],
    capabilities: ["text_to_video"],
    credits: 15,
    availability: "not_configured",
    outputType: "video",
  }),

  // —— Edit / Enhancer ——
  m({
    id: "canvas-edit",
    label: "Canvas Edit",
    provider: "krea",
    internalModel: "pending/canvas-edit",
    category: "edit",
    tools: ["edit"],
    capabilities: ["edit"],
    credits: 4,
    availability: "not_configured",
    outputType: "image",
    requires: ["source_image_url"],
  }),
  m({
    id: "expand-relight",
    label: "Expand / Relight",
    provider: "krea",
    internalModel: "pending/expand-relight",
    category: "edit",
    tools: ["edit"],
    capabilities: ["edit", "image_to_image"],
    credits: 4,
    availability: "not_configured",
    outputType: "image",
    requires: ["source_image_url"],
  }),
  m({
    id: "reference-input",
    label: "Reference Input",
    provider: "krea",
    internalModel: "pending/reference-input",
    category: "edit",
    tools: ["edit"],
    capabilities: ["edit", "image_to_image"],
    credits: 5,
    availability: "not_configured",
    outputType: "image",
    requires: ["source_image_url"],
  }),
  m({
    id: "topaz-pro-detail",
    label: "Pro Detail Innovation",
    provider: "krea",
    internalModel: "pending/topaz-pro-detail",
    category: "enhancer",
    endpointKind: "enhance",
    tools: ["enhancer"],
    capabilities: ["enhance", "upscale"],
    credits: 6,
    availability: "not_configured",
    outputType: "image",
    requires: ["source_image_url"],
  }),
  m({
    id: "topaz-max-22k",
    label: "Max Reality 22K",
    provider: "krea",
    internalModel: "pending/topaz-max-22k",
    category: "enhancer",
    endpointKind: "enhance",
    tools: ["enhancer"],
    capabilities: ["enhance", "upscale"],
    credits: 8,
    availability: "not_configured",
    outputType: "image",
    isPremium: true,
    requires: ["source_image_url"],
  }),
  m({
    id: "video-upscale",
    label: "Video Upscale",
    provider: "krea",
    internalModel: "pending/video-upscale",
    category: "enhancer",
    endpointKind: "enhance",
    tools: ["enhancer", "video"],
    capabilities: ["enhance", "upscale"],
    credits: 10,
    availability: "not_configured",
    outputType: "video",
    requires: ["source_video_url"],
  }),
  m({
    id: "qwen-edit",
    label: "Qwen Edit",
    provider: "krea",
    internalModel: "pending/qwen-edit",
    category: "edit",
    tools: ["edit"],
    capabilities: ["edit", "image_to_image"],
    credits: 4,
    availability: "not_configured",
    outputType: "image",
    requires: ["source_image_url"],
  }),

  // —— Lip sync ——
  m({
    id: "video-dialogue-sync",
    label: "Video Dialogue Sync",
    provider: "krea",
    internalModel: "pending/video-dialogue-sync",
    category: "lipsync",
    tools: ["lipsync"],
    capabilities: ["lipsync"],
    credits: 30,
    availability: "not_configured",
    outputType: "video",
    requires: ["source_video_url", "audio_url"],
  }),
  m({
    id: "upload-audio-sync",
    label: "Upload Audio Sync",
    provider: "krea",
    internalModel: "pending/upload-audio-sync",
    category: "lipsync",
    tools: ["lipsync"],
    capabilities: ["lipsync"],
    credits: 28,
    availability: "not_configured",
    outputType: "video",
    requires: ["source_video_url", "audio_url"],
  }),
  m({
    id: "generated-speech-sync",
    label: "Generated Speech Sync",
    provider: "krea",
    internalModel: "pending/generated-speech-sync",
    category: "lipsync",
    tools: ["lipsync"],
    capabilities: ["lipsync", "text_to_audio"],
    credits: 32,
    availability: "not_configured",
    outputType: "video",
  }),
  m({
    id: "fabric-lipsync",
    label: "Fabric",
    provider: "krea",
    internalModel: "pending/fabric",
    category: "lipsync",
    tools: ["lipsync"],
    capabilities: ["lipsync"],
    credits: 30,
    availability: "not_configured",
    outputType: "video",
  }),
  m({
    id: "hedra-lipsync",
    label: "Hedra",
    provider: "krea",
    internalModel: "pending/hedra",
    category: "lipsync",
    tools: ["lipsync"],
    capabilities: ["lipsync"],
    credits: 30,
    availability: "not_configured",
    outputType: "video",
  }),

  // —— Motion transfer ——
  m({
    id: "live-avatar",
    label: "Live Avatar",
    provider: "krea",
    internalModel: "pending/live-avatar",
    category: "motion_transfer",
    tools: ["motion_transfer"],
    capabilities: ["motion_transfer", "image_to_video"],
    credits: 25,
    availability: "not_configured",
    outputType: "video",
    requires: ["source_image_url"],
  }),
  m({
    id: "kling-motion-control",
    label: "Kling Motion Control",
    provider: "krea",
    internalModel: "pending/kling-motion-control",
    category: "motion_transfer",
    tools: ["motion_transfer"],
    capabilities: ["motion_transfer"],
    credits: 28,
    availability: "not_configured",
    outputType: "video",
  }),
  m({
    id: "runway-aleph",
    label: "Runway Aleph",
    provider: "krea",
    internalModel: "pending/runway-aleph",
    category: "motion_transfer",
    tools: ["motion_transfer", "video_restyle"],
    capabilities: ["motion_transfer", "video_to_video"],
    credits: 30,
    availability: "not_configured",
    outputType: "video",
  }),
  m({
    id: "wan-animate-replace",
    label: "Wan 2.2 Animate Replace",
    provider: "krea",
    internalModel: "pending/wan-animate-replace",
    category: "motion_transfer",
    tools: ["motion_transfer"],
    capabilities: ["motion_transfer"],
    credits: 25,
    availability: "not_configured",
    outputType: "video",
  }),
  m({
    id: "wan-animate-move",
    label: "Wan 2.2 Animate Move",
    provider: "krea",
    internalModel: "pending/wan-animate-move",
    category: "motion_transfer",
    tools: ["motion_transfer"],
    capabilities: ["motion_transfer"],
    credits: 25,
    availability: "not_configured",
    outputType: "video",
  }),

  // —— Video restyle ——
  m({
    id: "video-restyle",
    label: "Video Restyle",
    provider: "krea",
    internalModel: "pending/video-restyle",
    category: "video_restyle",
    tools: ["video_restyle"],
    capabilities: ["video_restyle", "video_to_video"],
    credits: 20,
    availability: "not_configured",
    outputType: "video",
    requires: ["source_video_url"],
  }),
  m({
    id: "restyle-preview",
    label: "Restyle Preview",
    provider: "krea",
    internalModel: "pending/restyle-preview",
    category: "video_restyle",
    tools: ["video_restyle"],
    capabilities: ["video_restyle"],
    credits: 10,
    availability: "not_configured",
    outputType: "video",
  }),
  m({
    id: "modify-video-style",
    label: "Modify Video / Style Transfer",
    provider: "krea",
    internalModel: "pending/modify-video-style",
    category: "video_restyle",
    tools: ["video_restyle"],
    capabilities: ["video_restyle", "video_to_video"],
    credits: 18,
    availability: "not_configured",
    outputType: "video",
  }),

  // —— 3D ——
  m({
    id: "object-render",
    label: "Object Render",
    provider: "krea",
    internalModel: "pending/object-render",
    category: "3d",
    tools: ["3d_objects"],
    capabilities: ["3d_object", "text_to_image"],
    credits: 4,
    availability: "not_configured",
    outputType: "mesh",
  }),
  m({
    id: "product-3d-style",
    label: "Product 3D Style",
    provider: "krea",
    internalModel: "pending/product-3d-style",
    category: "3d",
    tools: ["3d_objects", "product_photography"],
    capabilities: ["3d_object"],
    credits: 4,
    availability: "not_configured",
    outputType: "mesh",
  }),

  // —— Audio / workflow ——
  m({
    id: "voiceover-plan",
    label: "Voiceover Plan",
    provider: "krea",
    internalModel: "pending/voiceover-plan",
    category: "audio",
    tools: ["audio", "campaign_builder"],
    capabilities: ["text_to_audio", "planning"],
    credits: 5,
    availability: "not_configured",
    outputType: "audio",
  }),
  m({
    id: "campaign-planner",
    label: "Campaign Planner",
    provider: "krea",
    internalModel: "pending/campaign-planner",
    category: "workflow",
    tools: ["campaign_builder"],
    capabilities: ["planning", "workflow"],
    credits: 0,
    availability: "not_configured",
    outputType: "text",
  }),
  m({
    id: "batch-generator-planner",
    label: "Batch Generator Planner",
    provider: "krea",
    internalModel: "pending/batch-generator-planner",
    category: "workflow",
    tools: ["batch_generator"],
    capabilities: ["workflow", "planning"],
    credits: 0,
    availability: "not_configured",
    outputType: "text",
  }),
] as const;
